extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_carpet_i8[];
extern u8 castle_grounds_dl_bricks_i4[];
extern u8 castle_grounds_dl_brickscolor_rgba16[];
extern Vtx castle_grounds_dl_Cube_mesh_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_vtx_0[64];
extern Gfx castle_grounds_dl_Cube_mesh_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[215];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_Carpet_layer1[];
extern Gfx mat_revert_castle_grounds_dl_Carpet_layer1[];
extern Gfx mat_castle_grounds_dl_Bricks_layer1[];
extern Gfx mat_revert_castle_grounds_dl_Bricks_layer1[];
extern Gfx castle_grounds_dl_Cube_mesh[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
