extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Bus_Tread_lights;
extern u8 bob_dl_busenv_ci4[];
extern u8 bob_dl_busenv_ci4_pal_rgba16[];
extern u8 bob_dl_bustread_ci4[];
extern u8 bob_dl_bustread_ci4_pal_rgba16[];
extern u8 bob_dl_buswheel_i8[];
extern u8 bob_dl_buswindow_ia4[];
extern u8 bob_dl_busshroom_ia4[];
extern u8 bob_dl_bricks_i4[];
extern u8 bob_dl_brickscolor_rgba16[];
extern Vtx bob_dl_Bus_Visual_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Bus_Visual_mesh_layer_1_vtx_0[102];
extern Gfx bob_dl_Bus_Visual_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Bus_Visual_mesh_layer_1_vtx_1[76];
extern Gfx bob_dl_Bus_Visual_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Bus_Visual_mesh_layer_1_vtx_2[64];
extern Gfx bob_dl_Bus_Visual_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Bus_Visual_mesh_layer_2_vtx_cull[8];
extern Vtx bob_dl_Bus_Visual_mesh_layer_2_vtx_0[8];
extern Gfx bob_dl_Bus_Visual_mesh_layer_2_tri_0[];
extern Vtx bob_dl_Bus_Visual_mesh_layer_2_vtx_1[8];
extern Gfx bob_dl_Bus_Visual_mesh_layer_2_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[25];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Bus_Paint[];
extern Gfx mat_revert_bob_dl_Bus_Paint[];
extern Gfx mat_bob_dl_Bus_Tread[];
extern Gfx mat_revert_bob_dl_Bus_Tread[];
extern Gfx mat_bob_dl_Bus_Wheel[];
extern Gfx mat_bob_dl_Bus_Window_layer2[];
extern Gfx mat_revert_bob_dl_Bus_Window_layer2[];
extern Gfx mat_bob_dl_Bus_Shroom_layer2[];
extern Gfx mat_revert_bob_dl_Bus_Shroom_layer2[];
extern Gfx mat_bob_dl_Bricks_layer1[];
extern Gfx mat_revert_bob_dl_Bricks_layer1[];
extern Gfx bob_dl_Bus_Visual_mesh_layer_1[];
extern Gfx bob_dl_Bus_Visual_mesh_layer_2[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
